#define PORT_DEFAUT "1111"
#define PROTOCOLE_DEFAUT "udp"
#define SERVEUR_DEFAUT "localhost"
#define LongNomProtocole 4
#define LongMaxServeur 50
#define LongMaxService 100
#define FANNNAME "annuaire.db"
#define FCATNAME "catalogue.db"
#define WErrAnn -1
#define WErrCat -2
#define RErrAnn -1
#define RErrCat -2
