#define PORT_DEFAUT "1111"
#define PROTOCOLE_DEFAUT "udp"
#define SERVEUR_DEFAUT "localhost"
#define PROTOCOL_LMAX 4
#define SERV_LMAX 50
#define PORT_LMAX 100
#define F_ANN_NAME "annuaire.db"
#define F_CAT_NAME "catalogue.db"
#define ADHS_NBMAX 50
